// Simulated backend API. Do not edit this file — call these functions
// correctly from TaskBoard.jsx.

let _tasks = [
  { id: 1, title: 'Set up local environment', done: true },
  { id: 2, title: 'Read CONTRIBUTING.md', done: false }
]
let _nextId = 3

/**
 * Fetches the current task list from the "server".
 * @returns {Promise<Array<{id: number, title: string, done: boolean}>>}
 */
export function fetchTasks() {
  return new Promise((resolve) => {
    setTimeout(() => resolve([..._tasks]), 50)
  })
}

/**
 * Saves a new task to the "server" and returns the created task
 * (including its server-assigned id).
 * @param {{title: string, done: boolean}} task
 * @returns {Promise<{id: number, title: string, done: boolean}>}
 */
export function saveTask(task) {
  return new Promise((resolve) => {
    setTimeout(() => {
      const created = { id: _nextId++, title: task.title, done: !!task.done }
      _tasks = [..._tasks, created]
      resolve(created)
    }, 50)
  })
}

/**
 * Updates an existing task on the "server".
 * @param {number} id
 * @param {Partial<{title: string, done: boolean}>} changes
 * @returns {Promise<{id: number, title: string, done: boolean}>}
 */
export function updateTask(id, changes) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const idx = _tasks.findIndex((t) => t.id === id)
      if (idx === -1) return reject(new Error('Task not found'))
      _tasks[idx] = { ..._tasks[idx], ...changes }
      resolve(_tasks[idx])
    }, 50)
  })
}

/**
 * Deletes a task from the "server".
 * @param {number} id
 * @returns {Promise<{success: boolean}>}
 */
export function deleteTask(id) {
  return new Promise((resolve) => {
    setTimeout(() => {
      _tasks = _tasks.filter((t) => t.id !== id)
      resolve({ success: true })
    }, 50)
  })
}
